SOCIAL_AUTH_TWITTER_KEY = ' IDDyDIvIVgPRmaDmdgusahoxG'
SOCIAL_AUTH_TWITTER_SECRET = ' jk7fd9Uvc3S0t5xifnVVy5VJBeXKqLzOUr2GkPlMx4f7pG6qHk'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'
