# Generated by Django 2.0 on 2018-08-25 02:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('screen_name', models.CharField(max_length=20, primary_key='True', serialize=False)),
                ('latest_tweet_id', models.BigIntegerField()),
                ('chain', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UseCount',
            fields=[
                ('screen_name', models.CharField(max_length=20, primary_key='True', serialize=False)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
